FROM node:22-alpine
# Usamos la versión 22 para evitar el error de "Unsupported engine" que te salía

RUN apk add --no-cache git

WORKDIR /app

# Instalamos sass de forma global
RUN npm install -g sass

# No ponemos ENTRYPOINT fijo para que nos deje ejecutar npm create vite o npm run dev
CMD ["sh"]