FROM httpd:2.4

RUN mkdir -p /var/www/vite-project

COPY ./simulacre/carpetaApache/httpd.conf /usr/local/apache2/conf/httpd.conf
COPY ./simulacre/carpetaApache/httpd-vhosts.conf /usr/local/apache2/conf/extra/httpd-vhosts.conf


